# config/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8091']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'uber-query'
    static_configs:
      - targets: ['host.docker.internal:9404']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
